apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: {{.Release.Namespace}}
spec:
  serviceName: "kafka-service"
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: {{.Values.image}}:{{.Values.version}}
          imagePullPolicy: {{.Values.imagePullPolicy}}
          ports:
            - containerPort: 9092
              name: internal
            - containerPort: 29092
              name: external
            - containerPort: 9093
              name: controller
          volumeMounts:
            - name: kafka-storage
              mountPath: /var/lib/kafka/data
          env:
            - name: KAFKA_PROCESS_ROLES
              value: "broker,controller"

            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"

            - name: KAFKA_LISTENERS
              value: "INTERNAL://:9092,EXTERNAL://:29092,CONTROLLER://:9093"

            - name: KAFKA_ADVERTISED_LISTENERS
              value: "INTERNAL://kafka-service.{{.Release.Namespace}}.svc.cluster.local:9092,EXTERNAL://localhost:29092,CONTROLLER://kafka-service:9093"

            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"

            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "INTERNAL"

            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@kafka-service:9093"

            - name: KAFKA_NODE_ID
              value: "1"

            - name: KAFKA_LOG_DIRS
              value: "/var/lib/kafka/data"

            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"

            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"

            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
      volumes:
        - name: kafka-storage
          persistentVolumeClaim:
            claimName: kafka-pvc
